mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *
from blog import views
#날짜와 관련된 제네릭 뷰 정의
urlpatterns = [
    #/blog/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:index
    url(r'^$', PostLV.as_view(), name='index'),
    
    url(r'^post/(?P<pk>[0-9]+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', comment_remove, name='comment_remove'),

    #/blog/post/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:list
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    #/blog/post/영단어 요청을 처리할 뷰 클래스를 PostDV로 정의. 패턴이름은 blog:detail
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    #/blog/archive 요청을 처리할 뷰 클래스를 PostAV로 정의. 패턴이름은 blog:archive
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #/blog/4자리숫자 요청을 처리할 뷰 클래스를 PostYAV로 정의. 패턴이름은 blog:post_year_archive'
    url(r'^post/(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    #/blog/4자리숫자/3자리소문자 요청을 처리할 뷰 클래스를 PostMAV로 정의. 패턴이름은 blog:post_month_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    #/blog/4자리숫자/3자리소문자 /1~2숫자소문자 요청을 처리할 뷰 클래스를 PostDAV로 정의. 패턴이름은 blog:post_day_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    #/blog/today 요청을 처리할 뷰 클래스를 PostTAV로 정의. 패턴이름은 blog:post_today_archive'
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    url(r'^add/$', PostCreateView.as_view(), name="add", ),

    url(r'^change/$', PostChangeLV.as_view(), name="change", ),

    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update", ),

    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete", ),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')), #인증기능의 url은 보통 accounts로 시작
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^main_list/', include('main_list.urls', namespace='main_list')),


]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <title>{% block title %}Web programming{% endblock %}</title>

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

  <div id="header">
    <h2 class = "maintitle">Board</h2>
    {% if user.is_active %}
    <h4 class = "welcome">Welcome,
      <strong>{% firstof user.get_short_name user.get_username %}</strong> /
      <a href="{% url 'password_change' %}">Change Password</a> /
      <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class = "welcome">Welcome, Anonymous /
      <a href="{% url 'login' %}">Login</a> /
      <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
  </div>

<div id="menu">
  <li><a href="{% url 'home' %}">Home</a></li>
  <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
  <li><a href="{% url 'blog:index' %}">Blog</a></li>

  <li><a href="#">Add&bigtriangledown;</a>
    <ul>
      <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
      <li><a href="{% url 'blog:add' %}">Blog</a></li>
    </ul>
  </li>

  <li><a href="#">Change&bigtriangledown;</a>
    <ul>
      <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
      <li><a href="{% url 'blog:change' %}">Blog</a></li>
    </ul>
  </li>

  <li><a href="{% url 'main_list:index' %}">Nsight</a></li>
  <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>
  {% block content %}{% endblock %} <!--하위 페이지마다 실제 본문 내용 정의 -->

  {% block footer %}{% endblock %}  <!-- 하위 페이지마다 꼬리말을 다르게 정의 -->
</body>
</html>

mysite/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
<div id="content_home">

  <div id="homeimg">
    <a href="/"><img src="{% static '' %}" style="height:256px" /></a>
    <h4 style="margin: 0;"> this is django web site</h4>
  </div>

  <hr style="margin: 5px 0;">

  <h2>select application</h2>

  <table id="applist">
    <tr>
      <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
      <td>you can write your own post and share to other.you can write your own post and share to other.you can write your own post and share to other.you can write your own post and share to other.</td>
      <td class="Edit"><i><a href="#">Add</a></i></td>
      <td class="Edit"><i><a href="#">Change</a></i></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
      <td>you can write your own post and share to other.</td>
      <td class="Edit"><i><a href="#">Add</a></i></td>
      <td class="Edit"><i><a href="#">Change</a></i></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:index' %}">Nsight</a></i></b></td>
      <td>you can write your own post and share to other.</td>
      <td class="Edit"><i><a href="#">Add</a></i></td>
      <td class="Edit"><i><a href="#">Change</a></i></td>
    </tr>
  </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
  this is footer area
</div>
{% endblock footer %}