mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *
from blog import views
#날짜와 관련된 제네릭 뷰 정의
urlpatterns = [
    #/blog/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:index
    url(r'^$', PostLV.as_view(), name='index'),
    
    url(r'^post/(?P<pk>[0-9]+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', comment_remove, name='comment_remove'),

    #/blog/post/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:list
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    #/blog/post/영단어 요청을 처리할 뷰 클래스를 PostDV로 정의. 패턴이름은 blog:detail
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    #/blog/archive 요청을 처리할 뷰 클래스를 PostAV로 정의. 패턴이름은 blog:archive
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #/blog/4자리숫자 요청을 처리할 뷰 클래스를 PostYAV로 정의. 패턴이름은 blog:post_year_archive'
    url(r'^post/(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    #/blog/4자리숫자/3자리소문자 요청을 처리할 뷰 클래스를 PostMAV로 정의. 패턴이름은 blog:post_month_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    #/blog/4자리숫자/3자리소문자 /1~2숫자소문자 요청을 처리할 뷰 클래스를 PostDAV로 정의. 패턴이름은 blog:post_day_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    #/blog/today 요청을 처리할 뷰 클래스를 PostTAV로 정의. 패턴이름은 blog:post_today_archive'
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    url(r'^add/$', PostCreateView.as_view(), name="add", ),

    url(r'^change/$', PostChangeLV.as_view(), name="change", ),

    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update", ),

    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete", ),

]

mysite/main_list/urls.py
from django.conf.urls import url
from main_list.views import *


urlpatterns = [

url(r'^$', PostMysql.as_view(), name='index'),
url(r'^main_list/$', PostApache.as_view(), name='apache'),
url(r'^main_list/$', PostServer.as_view(), name='server'),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')), #인증기능의 url은 보통 accounts로 시작
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^main_list/', include('main_list.urls', namespace='main_list')),


]

mysite/main_list/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models

class Student(models.Model):
    _id = models.CharField(db_column='_id', max_length=9, blank=True, null=True)  # Field renamed because it started with '_'.
    name = models.CharField(max_length=48)
    belong = models.CharField(max_length=5, blank=True, null=True)
    phone = models.CharField(max_length=11, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'student'
        verbose_name = 'post'
        verbose_name_plural = 'posts' #복수의 별칭을 posts로

    def __str__(self):
        return self._id

mysite/main_list/views.py
from django.shortcuts import render
from main_list.models import Student
from django.views.generic import ListView
# Create your views here.
class PostMysql(ListView):
    model = Student
    template_name = 'main_list/all.html'

class PostApache(ListView):
    model = Student
    template_name = 'main_list/apache.html'

class PostServer(ListView):
    model = Student
    template_name = 'main_list/server.html'



#    def index(request):
#        post_list = Post.objects.all()
#        return render(request, 'all.html'), {

#            'post_list' : post_list,
#    }

mysite/main_list/templates/main_list/all.html
{% extends "base.html" %}

{% block title %}all.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id = "content">
<!--
  <table id="applist">
    <tr>
      <td><b><i><a href="{% url 'main_list:server' %}">Server</a></i></b></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:apache' %}">Apache</a></i></b></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:index' %}">Tomcat</a></i></b></td>
    </tr>
  </table>
-->
  <h1>Tomcat</h1>
<h4>Max Threads</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.2.1.1&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>Current thread count</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.2.1.4&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>Current thread busy</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.2.1.5&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>Request Count</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.2.1.8&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">


<h1>Server</h1>
<h4>used</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.1.1&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>idle</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.1.2&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>memory used</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.3.1&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>memory cached</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.3.6&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">

<h1>Apache</h1>
<h4>request/second</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.3&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>request/second</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.2&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>Max Threads</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.1&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">
<h4>Current thread busy</h4>
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.5&rt=img&interval=5&fdt=201712150000&tdt=201712260000" width="550" height="200">


</div>
{% endblock %}

mysite/main_list/templates/main_list/apache.html
{% extends "base.html" %}

{% block title %}apache.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id = "content">
  <table id="applist">
    <tr>
      <td><b><i><a href="{% url 'main_list:server' %}">Server</a></i></b></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:apache' %}">Apache</a></i></b></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:index' %}">Tomcat</a></i></b></td>
    </tr>
  </table>
    <h1>Apache</h1>

<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.3&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.2&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.1&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=2.1.1.5&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">

</div>
{% endblock %}

mysite/main_list/templates/main_list/server.html
{% extends "base.html" %}

{% block title %}server.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id = "content">
  <table id="applist">
    <tr>
      <td><b><i><a href="{% url 'main_list:server' %}">Server</a></i></b></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:apache' %}">Apache</a></i></b></td>
    </tr>

    <tr>
      <td><b><i><a href="{% url 'main_list:index' %}">Tomcat</a></i></b></td>
    </tr>
  </table>
  <h1>Server</h1>

<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.1.1&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.1.2&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.1.3&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">
<img src="http://api.nsight.nhncorp.com/monapi/api/request?r=R-20150923-001&k=dev-platform-ojt003.ncl&locale=ko-KR&data=1.1.1.4&rt=img&interval=5&fdt=201712150000&tdt=201712160000" width="550" height="200">

</div>
{% endblock %}