mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *
from blog import views
#날짜와 관련된 제네릭 뷰 정의
urlpatterns = [
    #/blog/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:index
    url(r'^$', PostLV.as_view(), name='index'),
    
    url(r'^post/(?P<pk>[0-9]+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', comment_remove, name='comment_remove'),

    #/blog/post/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:list
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    #/blog/post/영단어 요청을 처리할 뷰 클래스를 PostDV로 정의. 패턴이름은 blog:detail
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    #/blog/archive 요청을 처리할 뷰 클래스를 PostAV로 정의. 패턴이름은 blog:archive
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #/blog/4자리숫자 요청을 처리할 뷰 클래스를 PostYAV로 정의. 패턴이름은 blog:post_year_archive'
    url(r'^post/(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    #/blog/4자리숫자/3자리소문자 요청을 처리할 뷰 클래스를 PostMAV로 정의. 패턴이름은 blog:post_month_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    #/blog/4자리숫자/3자리소문자 /1~2숫자소문자 요청을 처리할 뷰 클래스를 PostDAV로 정의. 패턴이름은 blog:post_day_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    #/blog/today 요청을 처리할 뷰 클래스를 PostTAV로 정의. 패턴이름은 blog:post_today_archive'
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    url(r'^add/$', PostCreateView.as_view(), name="add", ),

    url(r'^change/$', PostChangeLV.as_view(), name="change", ),

    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update", ),

    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete", ),

]

mysite/bookmark/urls.py
from django.conf.urls import url
from bookmark.views import *

urlpatterns = [

    url(r'^bookmark/$', BookmarkLV.as_view(), name='index'),
    url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
    url(r'^add/$', BookmarkCreateView.as_view(), name='add'),
    url(r'^change/$', BookmarkChangeLV.as_view(), name='change'),
    url(r'^/(?P<pk>[0-9]+)/update/$', BookmarkUpdateView.as_view(), name='update'),
    url(r'^/(?P<pk>[0-9]+)/delete/$', BookmarkDeleteView.as_view(), name='delete'),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')), #인증기능의 url은 보통 accounts로 시작
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^main_list/', include('main_list.urls', namespace='main_list')),


]

mysite/bookmark/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User

class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True)

    def __str__(self):
        return self.title

mysite/bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

#LoginRequiredMixin, CreateView를 상속받아 BookmarkCreateView 작성. 로그인된 경우만 접근 가능
class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url'] #폼울 보여줄 때 'title', 'url' 필드에 대한 입력폼을 보여줌
    success_url = reverse_lazy('bookmark:index')
    def from_vaild(self, form):
        form.instance.owner = self.request.username #owner 필드에 현재 로그인된 유저 객체 할당
        return super(BookmarkCreateView, self).form_valid(form) #CreateView 클래스의 form_valid() 메소드 호출

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'
    def get_queryset(self): #화면에 출력할 레코드 리스트 반환
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

mysite/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark List{% endblock %}

{% block content %}
  <div id = "content">
    <h1>{{ object.title }}</h1>
    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
  </div>

{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
  <div id = "content">

    <h1>bookmark create/update - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

      {% if form.errors %}
      <p class="errornote">worng!</p>
      {% endif %}

      <p>this is a creation or update form for your bookmark</p>

      <fieldset class="aligned">

        <div class="form-row">
          {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-row">
          {{ form.url.label_tag }} {{ form.url }}
        </div>

      </fieldset>
        <div class="submit-row">
          <input type="submit" value="Submit"/>
        </div>
      <script type="text/javascript">document.getElementById('id_title').focus();
      </script>

    </form>

</div>
{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_list.html
<!--
<!DOCTYPE html>
<html>
<head>
<title>Django Bookmark List</title>
</head>
-->

{% extends "base.html" %}

{% block title %}Django Bookmark List{% endblock %}

{% block content %}
  <div id = "content">
    <h1>Bookmark List</h1>
    <ul>
      {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
  </div>
{% endblock %}