mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *
from blog import views
#날짜와 관련된 제네릭 뷰 정의
urlpatterns = [
    #/blog/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:index
    url(r'^$', PostLV.as_view(), name='index'),
    
    url(r'^post/(?P<pk>[0-9]+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', comment_remove, name='comment_remove'),

    #/blog/post/ 요청을 처리할 뷰 클래스를 PostLV로 정의. 패턴이름은 blog:list
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    #/blog/post/영단어 요청을 처리할 뷰 클래스를 PostDV로 정의. 패턴이름은 blog:detail
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    #/blog/archive 요청을 처리할 뷰 클래스를 PostAV로 정의. 패턴이름은 blog:archive
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    #/blog/4자리숫자 요청을 처리할 뷰 클래스를 PostYAV로 정의. 패턴이름은 blog:post_year_archive'
    url(r'^post/(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    #/blog/4자리숫자/3자리소문자 요청을 처리할 뷰 클래스를 PostMAV로 정의. 패턴이름은 blog:post_month_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    #/blog/4자리숫자/3자리소문자 /1~2숫자소문자 요청을 처리할 뷰 클래스를 PostDAV로 정의. 패턴이름은 blog:post_day_archive'
    url(r'^post/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    #/blog/today 요청을 처리할 뷰 클래스를 PostTAV로 정의. 패턴이름은 blog:post_today_archive'
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    url(r'^add/$', PostCreateView.as_view(), name="add", ),

    url(r'^change/$', PostChangeLV.as_view(), name="change", ),

    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView.as_view(), name="update", ),

    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name="delete", ),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')), #인증기능의 url은 보통 accounts로 시작
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^main_list/', include('main_list.urls', namespace='main_list')),


]

mysite/blog/models.py
 # -*- coding: utf-8 -*- 

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('modify_date', auto_now=True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'post' #테이블의 별칭을 단수와 복수로 가질 수 있는데, 단수 별칭을 post로
        verbose_name_plural = 'post_list' #복수의 별칭을 posts로
        db_table = 'my_post'
        ordering = ('-modify_date',) #모델 객체의 리스트 출력시 modify_date 컬러을 기준으로 내림차순 정렬

    def __str__(self):
        return self.title

    def get_absolute_url(self): #이 매소드가 정의된 객체를 지칭하는 url을 반환
        return reverse('blog:post_detail', args=(self.slug,)) #매소드 내에서는 장고의 내장함수인 reverse() 호출

    def get_previous_post(self): #modify_date 컬럼을 기준으로 이전 포스트 반환
        return self.get_previous_by_modify_date()

    def get_next_post(self): #modify_date 컬럼을 기준으로 다음 포스트 반환
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True) #처음으로 저장하는 경우에만 slug 필드를 title 필드의 단어로 변환해 자동으로 저장
        super(Post, self).save(*args, **kwargs)

    def approved_comments(self):
    return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text
# Create your models here.

mysite/blog/forms.py
from django import forms
from blog.models import Comment, Post

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

mysite/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blog.models import Post

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from mysite.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.forms import CommentForm
from django.shortcuts import render, redirect, get_object_or_404
# Create your views here.
#ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 5

#Detail views
class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    #title 필드로부터 자동으로 채워짐.레코드 생성폼을 보여줄 때 slug 필드를 입력하지 말라는 의미의 촐기값
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    print (post)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(reverse('blog:post_detail', args=(post.slug,)))
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
#    return redirect('blog:post_detail', pk=comment.post.pk)
    return redirect(reverse('blog:post_detail', args=(comment.post.slug,)))
@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.slug
    comment.delete()
#    return redirect('blog:post_detail', pk=post_pk)
    return redirect(reverse('blog:post_detail', args=(post_slug,)))

mysite/blog/templates/blog/add_comment_to_post.html
{% extends "base.html" %}

{% block title %}add_comment_to_post.html{% endblock %}

{% block content %}
<div id="content">
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

mysite/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<div id="content">

<h1>blog list</h1>  <!--별도의 태그가 없으면 장고는 body로 간주 -->
<table cellspacing=1 width=700 border=5>
    <tr>
        <td width=50><p align=center>번호</p></td>
        <td width=300><p align=center>제목</p></td>
        <td width=200><p align=center>등록일</p></td>
        <td width=100><p align=center>slug</p></td>
    </tr>
<ul>
{% for post in posts %}
<tr>
  <td width=50><p align=center>{{ post.id }}</p></td>
  <td width=100><p align=center><h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2></p></td>
  <td width=100><p align=center>{{ post.modify_date|date:"N d, Y" }}</p></td>
  <td width=100><p align=center>{{ post.description }}</p></td>
</tr>
{% endfor %}
</ul>
</table>
&nbsp
<div>
  <span> <!--span 태그 내의 요소들은 같은 줄에 배치. 페이징을 위한 줄-->
    {% if page_obj.has_previous %} <!--page_obj는 장고의 page 객체가 들어있는 컨텍스크 변수. 현재 페이지를 기준으로 이전 페이지가 있는지 확인 -->
      <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
    {% endif %}

    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
    {% endif %}
  </span>
</div>
{% endblock %}

mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<div id="content">


<h1>Post Archives until {% now "N d, Y" %}</h1>  <!--별도의 태그가 없으면 장고는 body로 간주 -->
<ul>
  {% for date in date_list %}
  <li style = "display: inline;">
    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}" > Year-{{ date|date:"Y" }} </a></li>
{% endfor %}
</ul>
<br/>

<div>
  <ul> <!--span 태그 내의 요소들은 같은 줄에 배치. 페이징을 위한 줄-->
    {% for post in object_list %} <!--page_obj는 장고의 page 객체가 들어있는 컨텍스크 변수. 현재 페이지를 기준으로 이전 페이지가 있는지 확인 -->
      <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp&nbsp&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}post_change_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

  <h1>Post Change - {{user}}</h1>
  <table class="change-list">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {%  for item in object_list %}
    <tr>
      <td>{{ item.title }}</td>
      <td>{{ item.description }}</td>
      <td>{{ item.owner }}</td>
      <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
      <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>

</div>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
  <h1>Post Delete</h1>

  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" />
  </form>

</div>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<div id="content">

<table cellspacing=1 width=500 border=5>
  <tr>
    <td width=50><p align=center><h2>{{ object.title }}</p></h2></td>  <!--별도의 태그가 없으면 장고는 body로 간주 -->
  </tr>
<div class = "body">
<tr>
 <td> {{ object.content|linebreaks }}</td>
</tr>
</br>
</table>
<p class="other_posts">
  {% if object.get_previous_by_modify_date %}
  <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
{% endif %}

    {% if object.get_next_by_modify_date %} <!--page_obj는 장고의 page 객체가 들어있는 컨텍스크 변수. 현재 페이지를 기준으로 이전 페이지가 있는지 확인 -->
    |  <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post"> {{ object.get_next_post }} --&raquo;</a>
    {% endif %}
  </p>
  <p class = "date">{{ object.modify_date|date:"j F Y" }}</p> <!--object.modify_date|date를 j F Y 형식으로 출력 -->
</br>
<hr>


<a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
{% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
</div>
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}post_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>Post Create/Update - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your post.</p>

    <fieldset class="aligned">
        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
        <div class="form-row">
            {{ form.slug.label_tag }} {{ form.slug }}
        </div>
        <div class="form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>
        <div class="form-row">
            {{ form.content.label_tag }} {{ form.content }}
        </div>
    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}